### ISSUE TITLE
EncoderMaxSpeed

### ISSUE THREAD

**Issue by blabel3** [blabel3/MicdsRobotics#2]
We checked the max pulses per revolution and everything for the encoders,  but it moves significantly slower than it should. This is one of the reasons we're using RUN_USING_ENCODERS instead of RUN_TO_POSITION, but I don't feel like it's a valid one. There are a few reasons why I think this could have happened:

- Our data is wrong for the motors (not likely, but it's always good to double-check. Got the initial data from AndyMark)
- Our calculations are wrong, possibly not factoring in the other three wheels if that's necessary (pretty likely)

- That's just how the max speed is; that's how fast it can go without skipping any values and that's just something we need to get used to.

**Comment by blabel3** [comment]
Right now it's set to 560, and it seems like it's going at about half as fast as it could be. Maybe the other wheels have that effect>

**Comment by blabel3** [comment]
We're using RUN_USING_ENCODER, and not having any issue anymore.

**Comment by dankmemes69** [comment]
sweg
